# Generated by Django 4.0.6 on 2022-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('PAID', 'Paid'), ('UNPAID', 'Upaid'), ('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('ARRIVED', 'Arrived')], default='...', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='used_coupon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
